### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by labpaw**

### CODE REVIEW

**Comment by labpaw** [comment]
Calling @Vexatos here. Come and translate :+1:

**Comment by Vexatos** [comment]
@VeryBigBro Thank's for the notice :+1: 
You should check http://crowdin.net/project/technic-launcher out.

**Comment by Adubbz** [comment]
There's a little translator club thing going on here :P

**Comment by labpaw** [comment]
@Vexatos I'll take a look at it.

**Pull request merged**
