### PR TITLE
404 Not found

### PR DESCRIPTION
**Pull request by ISTP7880**

### CODE REVIEW

**Comment by ISTP7880** [comment]
Not only 1.21.1 but also 1.21

**Comment by Forstride** [comment]
The file name is still messed up

**Comment by ISTP7880** [comment]
Fixed file name

**Comment by ISTP7880** [comment]
It has the same file name, so it should be Ko_kr.json, but I did it with Ko_kr.json.

**Comment by Forstride** [comment]
There's no reason you shouldn't be able to update the existing file properly, and I'm not gonna fix it manually, since you'll need to be able to do it properly yourself if you update it again or update it for one of our other mods or whatever.

**Comment by ISTP7880** [comment]
I tried to create a ko_kr.json file, but the same file was in that lang location.

**Comment by ISTP7880** [comment]
[ko_kr.json](https://github.com/user-attachments/files/16986617/ko_kr.json)

**Comment by ISTP7880** [comment]
Here is download link

**Comment by Forstride** [comment]
You shouldn't need to create a separate file, you should just be able to replace the existing one with your edits.  You can even just do it with the GitHub web editor...

Please learn how to make a pull request properly, because I'm not dealing with this if you have more edits in the future.

**Pull request closed without merging**
