### PR TITLE
Fix brewing recipes overriding vanilla recipes

### PR DESCRIPTION
**Pull request by KnightMiner**
For some odd reason, the built in Forge brewing recipe ignores NBT, causing the potion recipes added by this mod to replace all vanilla recipes (#229). To fix this, I simply added a NBT sensitive wrapper.

While making this change, I also fixed the missing potion names and cleaned up the recipe adding to go through two simple functions (making it a lot easier to add more effects in the future)

### CODE REVIEW

**Comment by Adubbz** [comment]
How strange... Oh well, looks good to me 👍

**Comment by liach** [comment]
Unfortunately this fix only applies to 1.11 versions. Would you backport it or accept a pull that backports it?

**Comment by KnightMiner** [comment]
Nothing of the code should be 1.11 specific, so he should be able to cherry pick the commit with no issue.

**Comment by liach** [comment]
Already cherry picked, now running to make sure it works

**Pull request merged**
