### PR TITLE
Added config option for crop death - Issue #184

### PR DESCRIPTION
**Pull request by isonym**
Added crop death config option as requested by @016Nojr in issue #184.

### CODE REVIEW

**Comment by Adubbz** [comment]
I think it'd be better to use Forge''s normal configuration setup for this, there's not really a reason the client needs to know about crop death being enabled or not

**Comment by Forstride** [comment]
I think that's fine.  The whole point is so you can access the options from the in-game menu

**Comment by isonym** [comment]
In retrospect I agree the client probably doesn't need to know.  I know very little about Forge and Minecraft modding in general, so that didn't occur to me, just copied the existing config options.

**Comment by Adubbz** [comment]
Fair enough. I'm not sure what Forstride is referring to, it's still possible to change options in the in-game menu with syncing them with the client

**Comment by Forstride** [comment]
Well it just looked like it copied the other options, so I wasn't really sure what the problem was.

**Comment by Adubbz** [comment]
Added this in 2.1.0

**Pull request closed without merging**
