### PR TITLE
404 Not found

### PR DESCRIPTION
**Pull request by ISTP7880**
Update and fix some Korean translations. Both 1.21 and 1.21.1

### CODE REVIEW

**Comment by ISTP7880** [comment]
fixed a few translations

**Comment by ISTP7880** [comment]
final fix

**Comment by Forstride** [comment]
For whatever reason, you created a file named "Update and fix some Korean translations" in the root of the Tough As Nails repo, instead of using ko_kr.json

Also in the previous PR you made on the 1.21 branch, you put the ko_kr.json file in the root of the TAN repo.  It needs to be in the lang folder with all of the other localization files.  Should've caught it myself before merging, but nonetheless...

**Comment by ISTP7880** [comment]
Sorry, This is my mistake.

**Comment by ISTP7880** [comment]
Please delete before created files. I will create it Lang folder.

**Pull request merged**
