### PR TITLE
Cherry picked brewing recipe fix for 1.10

### PR DESCRIPTION
**Pull request by liach**
Also I added git ignores for idea and fixed the missing run directory when trying to run in idea.

### CODE REVIEW

**Comment by liach** [comment]
@Adubbz @Forstride I just want to know if you are interested squash merging this and release a hotfix version because this totally destroys minecraft experience with potions (especially when with Not Enough Potions mod)

**Comment by liach** [comment]
Thanks!

**Comment by Adubbz** [comment]
Was trying to get an auto build made for this now that Jenkins is up, but that seems to be proving difficult... Hopefully it can be figured out since I'm guessing this won't be the last backport to 1.10 :P

**Comment by Adubbz** [comment]
And problem solved! Build should be up now

**Pull request merged**
