### PR TITLE
Tan 1.9.4 1.0.0

### PR DESCRIPTION
**Pull request by gigafunk**
Fix from 1.11
Not sure about the snapshot business, so I split the pull request.

Testing on a server with lots of mods now.

### CODE REVIEW

**Comment by liach** [comment]
I suggest working with an ide.

**Comment by gigafunk** [comment]
That would take care of the snapshot business?  Eh, too much trouble to add one line to some code. Take it or leave it. If they don't take the pull request people can just  build my fork. Its been working all night on the server and no one has crashed from this bug.

**Comment by liach** [comment]
This is some other mod's fault, not tan's.

**Comment by gigafunk** [comment]
Lol, its not about fault. Its about making Tan a little more robust to make it compatible with ply codes mods. Its ONE LINE of code.....

Are you suggesting this shouldn't be changed? I should dig through 189 more mods on my server to find the bug and fix it so some weird block can have a temperature?

**Comment by gigafunk** [comment]
*compatable with poorly coded mods

**Comment by KnightMiner** [comment]
If a block is not registered, they are doing something clearly wrong and its only a matter of time before it breaks something, including vanilla mechanics.

**Comment by gigafunk** [comment]
Well I am barely scriptkiddie level of coding. So I just copied the "not a fix" from 1.11.

Yes, some other mods give us trouble in that spot. Yes I WANT to track them down and fix them, in time I may be able to. But, they dont cause a client crash, so me and my 3 friends can deal with it, until I can track down. Might be easier to track down without crashing every time I get close. What's the big fn deal? Its a copied robustness feature from 1.11.Seeing as how there is a particle performance fix that IS tans FAULT that hasn't been fixed for 1.10, I am considerering 1.10 abandoned and will do my best to mirror higher version bug fixes and "robustness features"

**Comment by liach** [comment]
give the crash report then.

**Comment by gigafunk** [comment]
https://github.com/Glitchfiend/ToughAsNails/issues/255

**Comment by KnightMiner** [comment]
I was not aware the same code had been applied to later versions, though I still think the issue is on another mod as that should never be null. If the patch was applied to later versions it might be simpler to just cherry pick it though over a PR.

**Comment by gigafunk** [comment]
Author said pull request. I dont know cherry pick...I'm just trying to do
what I can and feel like you guys are trolling me. Had you been interested
in what i had to say instead of just nipping at my fn heels, you would have
saw the FIRST thing I typed was applying a "fix" from 1.11.

Sure its not a fix, its a "robustness feature" so maybe you didn't
understand me.  But either way, I'm done here. I'll do the best that I can
in my own fork and share my garbage versions as releases in git. If the
author doesn't like that, he can fix it and I will take down my "release".



On Jun 29, 2017 1:39 PM, "KnightMiner" <notifications@github.com> wrote:

I was not aware the same code had been applied to later versions, though I
still think the issue is on another mod as that should never be null. If
the patch was applied to later versions it might be simpler to just cherry
pick it though over a PR.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Glitchfiend/ToughAsNails/pull/283#issuecomment-312098949>,
or mute the thread

**Comment by gigafunk** [comment]
And I may be getting annoyed with these people busting my balls, but I do appreciate the work the authors put in for these. This was my attempt to give back, but its just not worth it. He said pull request, I thought I could handle that. Apparently I was wrong.

**Comment by KnightMiner** [comment]
You were perfectly free to mention any of that in the original PR comment though so people understood your intentions. As it stood, you were making a change without an IDE which included arbitrary changes to Forge and Minecraft versions that were not needed. And you did that without providing more description than "Testing This on Servers". Authors cannot be expected to take your word that your PR is useful, explain why it is for those who did not see that issue, or at least link to the issue *before* the PR is closed.

**Comment by gigafunk** [comment]
As far as I knew, glitchfiend was well aware of the issue, and I expected
him to be the guy looking at the request. I didn't expect the team that
looked at pull requests was like another division of a giant corporation.

Sure,llI should stay in the baby pool, but author/repository named owner
made it clear he wasn't going to do it. And that's fine since Mojang are
such jerks about making money off modders backs with no support or native
api making keeping up with all the versions a stupid chore.

I split the request, I thought that would allow just the added line of code.

When the change "worked" I said this was too easy. What is going to go
wrong. Well here it was, all this chatter about one line of code. Good word

**Review by liach — COMMENTED** [review]
Before returning you should spam the log on which block is bad, I guess.

**Comment by gigafunk** [comment]
That would be a great way to identify it and fix the root mod problem. I
think i can handle that, thanks for the suggestion!

**Comment by Adubbz** [comment]
I did have the same impression that this would indeed be the fault of some other mod. However, one thing I did notice whilst investigating this is that `getRegistryName` actually has a Nullable annotation, implying that the Forge devs knew this is possible. I have no idea why this is allowed in the first place, but nevertheless, it does seem to be their design decision so I figured a workaround would be suitable.

Cherrypicking this would've been ideal, and yeah, I don't really see why build.properties needed updating to be honest either

**Comment by gigafunk** [comment]
I thought it would be the only way to get it to build without an IDE.

**Comment by gigafunk** [comment]
Ok so I had it print the block to the log. it was an block from a mod we removed. a firelily or some such from ice&fire. I thought they just got deleted at world boot with the /fml confirm. I am guessing this explains why forge "expects" this from time to time. using world utill to delete them.

**Comment by KnightMiner** [comment]
Oh, this must be related to that Forge feature that persists old blocks in case you reinstall the mod. I wonder why they return a null registry name despite the registry name being the only way for Forge to know where to add them back in though.

Sorry for assuming this issue was not valid.

**Comment by gigafunk** [comment]
Like I said I need to stay in the kiddie pool, but I have learned quite a bit from this. Only way know how to learn I am afraid. Lol

**Comment by gigafunk** [comment]
https://minecraft.curseforge.com/projects/world-utils

That worked perfect to remove the blocks and some leftover entitys from mob mods, although its plenty clunky to use, its powerful.

**Pull request closed without merging**
